import type { QueryLanguageProfile } from "../provider-contract.js";

const fieldTags = [
  ["TS", "Topic", "Title + abstract + author keywords + Keywords Plus"],
  ["TI", "Title", "Article title only"],
  ["AB", "Abstract", "Abstract text"],
  ["AU", "Author", "Author name, e.g. AU=(De Marco* OR DeMarco*)"],
  ["AI", "Author Identifiers", "ORCID, ResearcherID, etc."],
  ["AK", "Author Keywords", "Author-assigned keywords"],
  ["KP", "Keywords Plus", "Algorithmically generated keywords from cited references"],
  ["SO", "Publication Name", "Journal or book series title"],
  ["DO", "DOI", "Digital Object Identifier"],
  ["PY", "Year Published", "Publication year or range: PY=2024, PY=(2020-2024)"],
  ["DOP", "Date of Publication", "Full date: DOP=2020-01-01/2020-03-01"],
  ["CF", "Conference", "Conference name"],
  ["AD", "Address", "Author address/affiliation text"],
  ["OG", "Organization-Enhanced", "Standardized institution name"],
  ["OO", "Organization", "Raw organization name"],
  ["CU", "Country/Region", "Country or region of author affiliation"],
  ["GP", "Group Author", "Corporate or group author name"],
  ["SU", "Research Area", "Broad research area classification"],
  ["WC", "Web of Science Category", "Specific subject category"],
  ["FO", "Funding Agency", "Funding organization name"],
  ["IS", "ISSN/ISBN", "Journal ISSN or book ISBN"],
  ["ED", "Editor", "Editor name"],
  ["UT", "Accession Number", "Web of Science unique record identifier"],
  ["PMID", "PubMed ID", "PubMed identifier"],
  ["LD", "Index Date", "Date record was indexed"],
  ["PUBL", "Publisher", "Publisher name"],
  ["ALL", "All Fields", "All searchable fields (excludes Funding Details)"],
].map(([code, label, description]) => ({ code, label, description }));

export const wosQueryProfile: QueryLanguageProfile = {
  provider: "wos",
  supportsRawEditor: true,
  supportsBuilderUi: true,
  supportsUrlQueryRecovery: false,
  rawEntryLabel: "Query Preview",
  fieldTags,
  booleanOperators: ["AND", "OR", "NOT"],
  proximityOperators: ["NEAR/x", "SAME"],
  wildcards: ["*", "?", "$"],
  examples: [
    "TS=(\"deep learning\") AND PY=(2020-2024)",
    "TI=(\"CRISPR\" OR \"gene editing\") AND WC=(Genetics & Heredity)",
    "TS=(\"machine learning\") AND OG=(Harvard University) AND PY=(2023)",
    "TS=((heart OR cardiac) NEAR/3 failure) AND PY=(2020-2024)",
  ],
  constraints: [
    "All Fields (ALL) queries are limited to 49 boolean or proximity operators.",
    "Quoted phrases disable lemmatization for the quoted term.",
    "In Title and Topic searches, at least 3 characters must precede right-hand wildcards.",
    "NEAR/x proximity: within x words, any order. Default NEAR = NEAR/15. NEAR/0 = adjacent.",
    "SAME: only for Address field — requires terms in same address block.",
    "Operator precedence: NEAR > SAME > NOT > AND > OR. Always use parentheses.",
    "IMPORTANT: DT (Document Type) and LA (Language) are NOT query field tags in current WOS. They can only be applied as post-search sidebar filters.",
    "PY cannot be used alone — must combine with another field via AND or NOT.",
    "Default behavior includes lemmatization (mouse → mice). Use quotes or Exact Search to disable.",
    "Wildcards: * (0+ chars), ? (1 char), $ (0 or 1 char). Not valid in PY or identifier fields.",
  ],
  recommendedPatterns: [
    "Prefer raw query entry through Query Preview for deterministic automation.",
    "Prefer explicit field tags instead of relying on assisted builder insertion.",
    "Use TS= for broad topic search; narrow with TI= or AK= for precision.",
  ],
  antiPatterns: [
    "Do not assume All Fields behaves like Topic — ALL excludes Funding Details.",
    "Do not exceed provider export batch limits without chunking.",
    "Do not use DT= or LA= in queries — they are not valid field tags in current WOS.",
  ],
};
