import type { QueryLanguageProfile } from "../provider-contract.js";

export const pubmedQueryProfile: QueryLanguageProfile = {
  provider: "pubmed",
  supportsRawEditor: true,
  supportsBuilderUi: true,
  supportsUrlQueryRecovery: true,
  rawEntryLabel: "Query box",
  fieldTags: [
    { code: "[ti]",     label: "Title",               description: "Words in article title" },
    { code: "[tiab]",   label: "Title/Abstract",      description: "Words in title or abstract" },
    { code: "[tw]",     label: "Text Word",           description: "All text fields: title, abstract, MeSH, keywords, etc." },
    { code: "[au]",     label: "Author",              description: "Author name, e.g. smith jb[au]" },
    { code: "[1au]",    label: "First Author",        description: "First listed author" },
    { code: "[lastau]", label: "Last Author",         description: "Last listed author" },
    { code: "[ad]",     label: "Affiliation",         description: "Author institutional affiliation" },
    { code: "[ta]",     label: "Journal",             description: "Journal title abbreviation, e.g. lancet[ta]" },
    { code: "[mh]",     label: "MeSH Terms",          description: "NLM Medical Subject Headings (auto-explodes). Use [mh:noexp] to disable" },
    { code: "[majr]",   label: "MeSH Major Topic",    description: "MeSH term as major focus of the article" },
    { code: "[sh]",     label: "MeSH Subheading",     description: "MeSH subheading qualifier, e.g. therapy[sh]" },
    { code: "[pt]",     label: "Publication Type",    description: "Review, Clinical Trial, Meta-Analysis, Systematic Review, Randomized Controlled Trial, Case Reports, Editorial, Letter" },
    { code: "[la]",     label: "Language",            description: "Language: english, chinese, french, german, japanese, spanish, etc." },
    { code: "[dp]",     label: "Date of Publication", description: "Year or range: 2020[dp], 2020:2024[dp], 2020/01/01:2024/12/31[dp]" },
    { code: "[sb]",     label: "Subset",              description: "Predefined subsets: medline, pubmed pmc, etc." },
    { code: "[ot]",     label: "Other Term",          description: "Non-MeSH keywords assigned by authors or submitters" },
    { code: "[doi]",    label: "DOI",                 description: "Digital Object Identifier" },
    { code: "[pmid]",   label: "PubMed ID",           description: "PubMed unique identifier" },
    { code: "[all]",    label: "All Fields",          description: "Searches all available fields" },
  ],
  booleanOperators: ["AND", "OR", "NOT"],
  proximityOperators: ["[field:~N]"],
  wildcards: ["*"],
  examples: [
    "\"deep learning\"[tiab] AND Review[pt]",
    "\"cancer\"[ti] AND 2020:2024[dp] AND english[la]",
    "\"CRISPR\"[tiab] AND Systematic Review[pt] AND \"gene editing\"[mh]",
  ],
  constraints: [
    "Boolean operators AND, OR, NOT must be UPPERCASE. PubMed processes left to right; use parentheses.",
    "Wildcard * is right-truncation only, minimum 4 characters before *.",
    "Proximity: \"term1 term2\"[field:~N] — within N words. Only supports [ti], [tiab], [ad]. Incompatible with wildcards.",
    "Automatic Term Mapping (ATM): untagged terms are auto-mapped to MeSH, journals, authors. Field tags, quotes, and wildcards disable ATM.",
    "MeSH terms auto-explode by default; use [mh:noexp] to disable.",
    "PubMed exports NBIB format (not RIS); server auto-converts to RIS.",
  ],
  recommendedPatterns: [
    "Prefer raw query entry when the agent has already formulated a full PubMed query.",
    "Use field tags to disable ATM for precise control over search behavior.",
    "Combine [mh] with [tiab] using OR for comprehensive topic coverage.",
  ],
  antiPatterns: [
    "Do not assume native RIS export exists; PubMed exports NBIB for citation manager flow.",
    "Do not rely on ATM for systematic reviews — always use explicit field tags.",
  ],
};
