import type { QueryLanguageProfile } from "../provider-contract.js";

export const ieeeQueryProfile: QueryLanguageProfile = {
  provider: "ieee",
  supportsRawEditor: true,
  supportsBuilderUi: true,
  supportsUrlQueryRecovery: true,
  rawEntryLabel: "Search query",
  fieldTags: [
    { code: "All Metadata",      label: "All Metadata",      description: "All metadata fields — default wide search" },
    { code: "Document Title",    label: "Document Title",    description: "Article/paper title" },
    { code: "Abstract",          label: "Abstract",          description: "Abstract text" },
    { code: "Author",            label: "Author",            description: "Author names" },
    { code: "Affiliation",       label: "Affiliation",       description: "Author institution" },
    { code: "Author Keywords",   label: "Author Keywords",   description: "Author-assigned keywords" },
    { code: "IEEE Terms",        label: "IEEE Terms",        description: "IEEE controlled vocabulary terms" },
    { code: "Index Terms",       label: "Index Terms",       description: "All index terms (IEEE + author + MeSH)" },
    { code: "MeSH Terms",        label: "MeSH Terms",        description: "Medical Subject Headings (biomedical papers)" },
    { code: "Publication Title",  label: "Publication Title",  description: "Journal or conference name" },
    { code: "DOI",               label: "DOI",               description: "Digital Object Identifier" },
    { code: "Publisher",         label: "Publisher",         description: "Publisher name" },
    { code: "Funding Agency",    label: "Funding Agency",    description: "Funding organization" },
  ],
  booleanOperators: ["AND", "OR", "NOT"],
  proximityOperators: ["NEAR/", "ONEAR/"],
  wildcards: ["*", "?"],
  examples: [
    "\"Document Title\":\"deep learning\" AND \"Abstract\":\"medical imaging\"",
    "(\"Author Keywords\":RFID OR \"Index Terms\":RFID) AND \"Publication Title\":\"IEEE Transactions on Consumer Electronics\"",
    "(\"Document Title\":telemedicine OR \"Index Terms\":telemedicine)",
  ],
  constraints: [
    "Field syntax: \"Field Name\":value. Exact phrase requires inner quotes: \"Document Title\":\"web services\".",
    "Boolean operators AND, OR, NOT must be ALL CAPS.",
    "Operator precedence: NEAR/ONEAR > NOT > AND > OR. Use parentheses to override.",
    "Wildcards: * (zero or more), ? (exactly one). Min 3 chars required. Max 10 wildcards per search.",
    "NEAR/# (unordered proximity), ONEAR/# (ordered proximity). Only in Advanced Search and command search.",
    "Multi-field topic search: combine Document Title, Abstract, Author Keywords, Index Terms with OR.",
    "IMPORTANT: Content type (Journals, Conferences, Standards) and year ranges CANNOT be filtered in query syntax. They are controlled via URL parameters or post-search facets.",
    "Export behavior differs between Results and Citations tabs.",
  ],
  recommendedPatterns: [
    "Prefer result-page sampling and inline abstract expansion before exporting.",
    "For comprehensive topic search, combine Document Title + Abstract + Author Keywords + Index Terms with OR.",
    "Use exact phrase with inner quotes for multi-word concepts.",
  ],
  antiPatterns: [
    "Do not assume results CSV export is the same as citation RIS export.",
    "Do not try to filter by year or content type in the query — use URL parameters instead.",
  ],
};
